version: "3.5"
services:
  db:
    image: postgres:10
    expose:
      - "5432"
    volumes:
      - "./shared/db/postgresql:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    logging: &logging
      driver: "gelf"
      options:
        gelf-address: "udp://your-graylog-server:12201"

  guacd:
    image: guacamole/guacd:1.0.0
    expose:
      - "4822"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    logging:
      <<: *logging

  guacamole:
    image: guacamole/guacamole:1.0.0
    expose:
      - "8080"
    environment:
      - POSTGRES_HOSTNAME=db
      - POSTGRES_DATABASE=guacamole_db
      - POSTGRES_USER=guacamole_user
      - POSTGRES_PASSWORD=your-postgres-root-pass
      - GUACAMOLE_HOME=/etc/guacamole
      - GUACD_HOSTNAME=guacd
      - POSTGRES_DEFAULT_MAX_CONNECTIONS=0
      - POSTGRES_DEFUALT_MAX_GROUP_CONNECTIONS=0
    depends_on:
      - db
      - guacd
    volumes:
      - "./shared/guacamole/etc/guacamole:/etc/guacamole"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    logging:
      <<: *logging

  nginx:
    image: really/nginx-modsecurity
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/pki:/etc/ssl"
      - "./shared/nginx/conf.d:/etc/nginx/conf.d"
      - "./shared/nginx/modsec/conf.d:/etc/nginx/modsec/conf.d"
      - "./shared/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./shared/nginx/modsec/crs-setup.conf:/usr/local/owasp-modsecurity-crs-3.0.0/crs-setup.conf"
      - "/var/log/dockermole/nginx/access.log:/var/log/nginx/access.log"
      - "/var/log/dockermole/nginx/error.log:/var/log/nginx/error.log"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    depends_on:
        - guacamole
    logging:
      <<: *logging
